# Generated by Django 3.1.7 on 2021-03-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
